#!/bin/bash

function runCompiz() {
	gtk-window-decorator &
	exec compiz --ignore-desktop-hints glib gconf $@
}

DIRECT=`glxinfo | grep "direct rendering: " | head -n 1 | cut -d " " -f 3`
ISSW=`glxinfo | grep "Software Rasterizer" -c`

# Disabled for now, does not work as expected
#HAVETFP=`glxinfo | grep texture_from_pixmap -c`

#if ( [ $HAVE3D == "Yes" ] && [ $HAVETFP -gt 2 ] ); then 
#	runCompiz $@
#fi

# Try again with indirect rendering
export LIBGL_ALWAYS_INDIRECT=1

HAVETFP=`glxinfo | grep texture_from_pixmap -c`

if ( [ $DIRECT == "Yes" ] && [ $ISSW == 0 ] && [ $HAVETFP -gt 2 ] ); then 
	runCompiz $@
fi

# Fall back to metacity
exec metacity $@
