#!/bin/bash

theme=`xfconf-query -c xfwm4 -p /general/theme`

echo "$theme"

function runCompiz() {
	gtk-window-decorator --replace --marco-theme "$theme" &
	exec compiz --replace --sm-disable --ignore-desktop-hints ccp $@ 
}

ISSW=`glxinfo | grep "Software Rasterizer" -c`

# Try with direct rendering
HAVETFP=`glxinfo | grep texture_from_pixmap -c`

if ( [ $ISSW == 0 ] && [ $HAVETFP -gt 2 ] ); then 
	runCompiz $@
fi

# Try again with indirect rendering
export LIBGL_ALWAYS_INDIRECT=1

HAVETFP=`glxinfo | grep texture_from_pixmap -c`

if ( [ $ISSW == 0 ] && [ $HAVETFP -gt 2 ] ); then 
	runCompiz $@
fi

# Fall back to xfwm4
exec xfwm4 $@

